removed_sources:
  Dist-Zilla-Plugin-ReportVersions-Tiny-1.02.tar.gz: 4da628aad302664c3de670bdd0ad095060c77d6a
sources:
  Dist-Zilla-Plugin-ReportVersions-Tiny-1.10.tar.gz: e23a0fa34ec82acd3fd09e9a3ceb3d3e61ab6587
